name: this is second attempt
on:
  push:
    branches: [ "main" ]
  pull_request:
   branches: [ "main" ]
jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:

      - name: step 1
        run:  echo "first step"

      - name: step 2
        run:  echo "second step"
  deploy-job:
   runs-on: ubuntu-latest   
      - name: install go
        uses: actions/setup-go@v5.5.0
